#############################################################################
## Configuration file of docker-composer.                                  ##
## You must create a .env file, based on .env.dist to configure services.  ##
#############################################################################
version: '3'

volumes:
  # Creates a Docker volume to persist data.
  postgres:

networks:
  default:
    external:
      name: umanit-php-stack-network

services:
  phpfpm:
    build:
      context: confs/php-fpm
      args:
        phptag: ${PHP_TAG:?Missing PHP_TAG}
    restart: always
    volumes:
      - ./www:/var/www/html
      # Use the next line instead of the previous one if you are using MacOS.
      # - ./www:/var/www/html:cached
      - ./logs/php-fpm:/var/log/php-fpm
      - ./confs/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./confs/php-fpm/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:${POSTGRES_TAG:?Missing POSTGRES_TAG}
    restart: always
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/log/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Missing POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    # Uncomment the following lines if you want to connect to PostgreSQL with
    # an external tool like PhpStorm, adminer, etc.
    # The host to use would be "postgres".
    # ports:
    #   - '5432:5432'

  nginx:
    image: nginx:${NGINX_TAG:?Missing NGINX_TAG}
    restart: always
    volumes:
      - ./www:/var/www/html
      # Use the next line instead of the previous one if you are using MacOS.
      # - ./www:/var/www/html:cached
      - ./confs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - phpfpm
      - postgres
    ports:
      - '${NGINX_PORT:-8080}:80'
    environment:
      - VIRTUAL_HOST=${SITE_URL:?Missing SITE_URL}
